services:
  db:
    image: postgres:latest
    container_name: property-db
    environment:
      POSTGRES_DB: propertydb
      POSTGRES_USER: property_user
      POSTGRES_PASSWORD: property_pass
    ports:
      - "5432:5432"
    volumes:
      - property-db-data:/var/lib/postgresql

  app:
    build: .
    container_name: property-service
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/propertydb
      SPRING_DATASOURCE_USERNAME: property_user
      SPRING_DATASOURCE_PASSWORD: property_pass
    ports:
      - "8080:8080"

volumes:
  property-db-data: